# Generated by Django 3.1.6 on 2021-03-06 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.apicustomization')),
            ],
            options={
                'db_table': 'api_title',
                'managed': True,
            },
        ),
    ]
