# Generated by Django 3.1.6 on 2021-03-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apititle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicustomization',
            old_name='livechat_placeholder_online',
            new_name='livechat_placeholder',
        ),
        migrations.RemoveField(
            model_name='apicustomization',
            name='livechat_placeholder_offline',
        ),
    ]
