# Generated by Django 3.1.6 on 2021-03-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210307_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apititle',
            name='customization',
        ),
        migrations.DeleteModel(
            name='ApiCustomization',
        ),
        migrations.DeleteModel(
            name='ApiTitle',
        ),
    ]
