# Generated by Django 3.1.6 on 2021-02-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('ip', models.CharField(blank=True, max_length=15, null=True)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_message',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CorePackage',
        ),
    ]
