# Generated by Django 3.1.6 on 2021-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='image',
            field=models.FileField(null=True, upload_to='A/'),
        ),
    ]
