# Generated by Django 3.1.6 on 2021-02-21 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='bio',
            field=models.CharField(blank=True, default='Howdy!', help_text='Max length: 30', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='city',
            field=models.CharField(blank=True, help_text='Max length: 30', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Letters allowed only!')]),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='country',
            field=models.CharField(blank=True, help_text='Max length: 30', max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Letters allowed only!')]),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='email',
            field=models.EmailField(help_text='Max length: 30', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='firstname',
            field=models.CharField(help_text='Max Length: 30', max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Letters allowed only!')]),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='image',
            field=models.FileField(blank=True, default=None, help_text='Size < 1Mb', null=True, upload_to='A/'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='lastname',
            field=models.CharField(help_text='Max Length: 30', max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Letters allowed only!')]),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='phonenumber',
            field=models.TextField(help_text='Format: XXXX XXX XXX', max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', message='Numbers allowed only!')]),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='username',
            field=models.CharField(help_text='Max length: 30', max_length=30, unique=True),
        ),
    ]
