# Generated by Django 3.1.6 on 2021-02-21 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210221_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='phonenumber',
            field=models.CharField(help_text='Format: XXXX XXX XXX', max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', message='Numbers allowed only!')]),
        ),
    ]
