# Generated by Django 3.1.6 on 2021-02-24 11:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210224_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 6, 43, 110257)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 6, 43, 108255)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='status',
            field=models.CharField(default='open', max_length=8, validators=[django.core.validators.RegexValidator('^{open|closed}$', message='Status Unknonw')]),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 15, 6, 43, 109255)),
        ),
    ]
