# Generated by Django 3.1.6 on 2021-02-24 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210224_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 6, 39, 241233)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 6, 39, 240237)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 6, 39, 240237)),
        ),
        migrations.CreateModel(
            name='CoreNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 6, 39, 242237), verbose_name='Published Date')),
                ('content', models.TextField(max_length=500)),
                ('tags', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.coreuser')),
            ],
            options={
                'db_table': 'core_newsletter',
                'managed': True,
            },
        ),
    ]
