# Generated by Django 3.1.6 on 2021-02-21 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210221_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='email',
            field=models.EmailField(help_text='Max length: 30', max_length=50, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Size < 1Mb', null=True, upload_to='A/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='phonenumber',
            field=models.CharField(help_text='Format: XXXX XXX XXX', max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='Numbers allowed only!')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.coresite', verbose_name='Assigned Site'),
        ),
    ]
