# Generated by Django 3.1.6 on 2021-02-24 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210224_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 10, 0, 253979)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 10, 0, 252981)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 10, 0, 252981)),
        ),
        migrations.DeleteModel(
            name='CoreNewsLetter',
        ),
    ]
