# Generated by Django 3.1.6 on 2021-02-22 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210222_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coresession',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 15, 50, 38, 252166)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 15, 50, 38, 253206)),
        ),
        migrations.CreateModel(
            name='CoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 15, 50, 38, 254166))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.coreuser')),
            ],
            options={
                'db_table': 'core_log',
                'managed': True,
            },
        ),
    ]
