# Generated by Django 3.1.6 on 2021-02-22 20:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210222_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='corelog',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.coresite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 23, 48, 36, 39235)),
        ),
        migrations.AlterField(
            model_name='coresession',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 23, 48, 36, 38185)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 23, 48, 36, 39235)),
        ),
    ]
