# Generated by Django 3.1.6 on 2021-03-02 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210228_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 15, 24, 28, 326814)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 15, 24, 28, 325767)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 15, 24, 28, 325767)),
        ),
    ]
