# Generated by Django 3.1.6 on 2021-03-05 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210302_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='is_online',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 21, 41, 24, 862281)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 21, 41, 24, 860280)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 21, 41, 24, 861284)),
        ),
    ]
