# Generated by Django 3.1.6 on 2021-03-05 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210306_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corecustomization',
            old_name='virtualagent_placeholder_online',
            new_name='virtualagent_placeholder',
        ),
        migrations.RemoveField(
            model_name='corecustomization',
            name='ticket_placeholder_online',
        ),
        migrations.AddField(
            model_name='corecustomization',
            name='ticket_placeholder',
            field=models.CharField(default='We will contact you by email.', max_length=30),
        ),
        migrations.AlterField(
            model_name='corecustomization',
            name='livechat_title',
            field=models.CharField(default='Start a Conversation', max_length=20),
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 30, 8, 778367)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 30, 8, 775366)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 30, 8, 776406)),
        ),
    ]
