# Generated by Django 3.1.6 on 2021-03-05 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210306_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corecustomization',
            name='placeholder',
            field=models.CharField(default='Ask us anything, or share your feedback.', max_length=40),
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 31, 9, 196428)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 31, 9, 194403)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 31, 9, 195430)),
        ),
    ]
