# Generated by Django 3.1.6 on 2021-03-05 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210306_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coresite',
            old_name='service',
            new_name='livechat_service',
        ),
        migrations.AddField(
            model_name='coresite',
            name='ticket_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coresite',
            name='virtualagent_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 38, 50, 35618)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 38, 50, 33592)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 38, 50, 34618)),
        ),
    ]
