# Generated by Django 3.1.6 on 2021-03-06 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210306_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreroom',
            name='topic',
            field=models.CharField(default='general', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 13, 8, 36, 163050)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 13, 8, 36, 162051)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 13, 8, 36, 163050)),
        ),
    ]
