# Generated by Django 3.1.6 on 2021-03-07 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210306_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 14, 42, 51, 827049)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 14, 42, 51, 825022)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 14, 42, 51, 825022)),
        ),
    ]
