# Generated by Django 3.1.6 on 2021-03-09 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210307_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coresite',
            old_name='name',
            new_name='host',
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 14, 40, 45, 390119)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 14, 40, 45, 389126)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 14, 40, 45, 389126)),
        ),
    ]
