# Generated by Django 3.1.6 on 2021-03-09 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210309_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coremessage',
            name='ip',
        ),
        migrations.AddField(
            model_name='coreroom',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 15, 57, 7, 246124)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 15, 57, 7, 245090)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 15, 57, 7, 245090)),
        ),
    ]
