# Generated by Django 3.1.6 on 2021-03-09 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210309_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coremessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='coremessage',
            name='client',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 16, 2, 28, 133996)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 16, 2, 28, 132998)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 16, 2, 28, 132998)),
        ),
    ]
