# Generated by Django 3.1.6 on 2021-03-10 06:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210309_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreuser',
            old_name='email',
            new_name='emailaddress',
        ),
        migrations.RenameField(
            model_name='coreuser',
            old_name='user_key',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='image',
        ),
        migrations.AddField(
            model_name='coreuser',
            name='assigned_rooms_count',
            field=models.IntegerField(default=0, verbose_name='Number of assigned rooms'),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='title',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Letters allowed only!')]),
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 4, 25, 820066)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 4, 25, 818070)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 4, 25, 819067)),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='firstname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Letters allowed only!')]),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='lastname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', message='Letters allowed only!')]),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='phonenumber',
            field=models.CharField(help_text='Format: XXXX XXX XXXX', max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='Numbers allowed only!')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='role',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('{staff|admin|agent}', message='Unknown Role')]),
        ),
    ]
