# Generated by Django 3.1.6 on 2021-03-10 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210310_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreuser',
            old_name='key',
            new_name='use_key',
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 6, 44, 509876)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 6, 44, 507875)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 6, 44, 507875)),
        ),
    ]
