# Generated by Django 3.1.6 on 2021-03-10 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210310_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coreuser',
            old_name='use_key',
            new_name='user_key',
        ),
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 7, 42, 164600)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 7, 42, 162603)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 10, 7, 42, 163601)),
        ),
    ]
