# Generated by Django 3.1.6 on 2021-03-10 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210310_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corelog',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 14, 48, 31, 45451)),
        ),
        migrations.AlterField(
            model_name='coreroom',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 14, 48, 31, 44441)),
        ),
        migrations.AlterField(
            model_name='coresite',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 14, 48, 31, 45451)),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
