# Generated by Django 3.1.6 on 2021-02-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('icon', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=10, null=True)),
                ('role', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'dashboard_menu',
                'managed': True,
            },
        ),
    ]
