# Generated by Django 3.1.6 on 2021-02-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardmenu',
            old_name='role',
            new_name='category',
        ),
    ]
