# Generated by Django 3.1.6 on 2021-03-10 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210310_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email address',
            field=models.EmailField(default='ipchi1380@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 18, 55, 3, 87436)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 18, 55, 3, 86433)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 18, 55, 3, 87436)),
        ),
    ]
