# Generated by Django 3.1.6 on 2021-02-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210223_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmenu',
            name='category',
            field=models.CharField(max_length=6),
        ),
    ]
