# Generated by Django 3.1.6 on 2021-03-10 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210310_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_rooms_count',
        ),
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 17, 21, 47, 271874)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 17, 21, 47, 270874)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 17, 21, 47, 270874)),
        ),
    ]
