# Generated by Django 3.1.6 on 2021-02-24 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210224_1610'),
        ('dashboard', '0003_auto_20210223_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardNewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2021, 2, 24, 16, 10, 0, 256930), verbose_name='Published Date')),
                ('content', models.TextField(max_length=500)),
                ('tags', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.coreuser')),
            ],
            options={
                'db_table': 'dashboard_newsletter',
                'managed': True,
            },
        ),
    ]
