# Generated by Django 3.1.6 on 2021-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboardnewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardnewsletter',
            name='date_published',
            field=models.DateTimeField(verbose_name='Published Date'),
        ),
    ]
