# Generated by Django 3.1.6 on 2021-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210226_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardnewsletter',
            name='content',
            field=models.TextField(help_text='Max Length: 500', max_length=500),
        ),
        migrations.AlterField(
            model_name='dashboardnewsletter',
            name='tags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardnewsletter',
            name='title',
            field=models.CharField(help_text='Max length: 50', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardnewsletter',
            name='type',
            field=models.CharField(choices=[('general', 'general'), ('maintenance', 'maintenance'), ('update', 'update')], default='general', max_length=30),
        ),
    ]
