# Generated by Django 3.1.6 on 2021-02-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210226_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReservedMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max Length: 30', max_length=30)),
                ('type', models.CharField(blank=True, default='general', help_text='Max Length: 30', max_length=30)),
                ('content', models.TextField(help_text='Max Length: 500', max_length=500)),
                ('starred', models.BooleanField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'dashboard_reservedmessages',
                'managed': True,
            },
        ),
    ]
