# Generated by Django 3.1.6 on 2021-03-13 18:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210310_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max length: 50', max_length=30)),
                ('date_published', models.DateTimeField(verbose_name='Published Date')),
                ('content', models.TextField(help_text='Max Length: 500', max_length=500)),
                ('tags', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_notification',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 22, 13, 33, 654706)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 22, 13, 33, 654706)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 22, 13, 33, 654706)),
        ),
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
