# Generated by Django 3.1.6 on 2021-02-28 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_dashboardreservedmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreservedmessages',
            name='date_modifies',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified Date'),
            preserve_default=False,
        ),
    ]
