# Generated by Django 3.1.6 on 2021-02-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210228_1918'),
        ('dashboard', '0008_dashboardreservedmessages_date_modifies'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreservedmessages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.coreuser'),
            preserve_default=False,
        ),
    ]
