# Generated by Django 3.1.6 on 2021-02-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dashboardreservedmessages_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardreservedmessages',
            old_name='date_modifies',
            new_name='date_modified',
        ),
    ]
