# Generated by Django 3.1.6 on 2021-03-13 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210313_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 0, 4, 30, 901992)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_opened',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 0, 4, 30, 900992)),
        ),
        migrations.AlterField(
            model_name='site',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 0, 4, 30, 900992)),
        ),
    ]
