# Generated by Django 3.1.6 on 2021-03-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210228_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardreservedmessages',
            name='type',
            field=models.CharField(blank=True, default='general', help_text='Max Length: 15', max_length=15),
        ),
    ]
