# Generated by Django 3.1.6 on 2021-03-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210302_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardreservedmessages',
            name='color',
            field=models.CharField(choices=[['INDIGO', 'indigo'], ['GREEN', 'green'], ['RED', 'red'], ['PURPLE', 'purple'], ['PINK', 'pink'], ['LIME', 'lime'], ['TEAL', 'teal'], ['CYAN', 'cyan']], default='GREEN', max_length=15),
        ),
    ]
