# Generated by Django 3.1.6 on 2021-03-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_dashboardreservedmessages_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardreservedmessages',
            old_name='type',
            new_name='tag',
        ),
    ]
