# Generated by Django 3.1.6 on 2021-03-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210303_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardreservedmessages',
            name='color',
            field=models.CharField(choices=[['INDIGO', 'indigo'], ['GREEN', 'green'], ['BLACK', 'black'], ['PURPLE', 'purple'], ['PINK', 'pink'], ['LIME', 'lime'], ['TEAL', 'teal'], ['CYAN', 'cyan'], ['BLUE', 'blue']], default='INDIGO', max_length=15),
        ),
    ]
